// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVVOkwI3f_A86MAcmsuD_qZA4LTQqZOZI',
    appId: '1:597426519405:web:31d8e084eda49bfc8eee64',
    messagingSenderId: '597426519405',
    projectId: 'habittracker-f8de2',
    authDomain: 'habittracker-f8de2.firebaseapp.com',
    storageBucket: 'habittracker-f8de2.firebasestorage.app',
    measurementId: 'G-5BJM7J58V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgznkWJmG5hLCJX_JW3SsGJPvI3YA_MO8',
    appId: '1:597426519405:android:b827475bc17405028eee64',
    messagingSenderId: '597426519405',
    projectId: 'habittracker-f8de2',
    storageBucket: 'habittracker-f8de2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClcXKYlcaK6yJrLavwaGl6sSuORMuT5Yw',
    appId: '1:597426519405:ios:f170efbf46305d088eee64',
    messagingSenderId: '597426519405',
    projectId: 'habittracker-f8de2',
    storageBucket: 'habittracker-f8de2.firebasestorage.app',
    iosBundleId: 'com.example.habbitTrackerGamify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClcXKYlcaK6yJrLavwaGl6sSuORMuT5Yw',
    appId: '1:597426519405:ios:f170efbf46305d088eee64',
    messagingSenderId: '597426519405',
    projectId: 'habittracker-f8de2',
    storageBucket: 'habittracker-f8de2.firebasestorage.app',
    iosBundleId: 'com.example.habbitTrackerGamify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVVOkwI3f_A86MAcmsuD_qZA4LTQqZOZI',
    appId: '1:597426519405:web:66763853df1615898eee64',
    messagingSenderId: '597426519405',
    projectId: 'habittracker-f8de2',
    authDomain: 'habittracker-f8de2.firebaseapp.com',
    storageBucket: 'habittracker-f8de2.firebasestorage.app',
    measurementId: 'G-DW0EK9D85D',
  );
}
